# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd

## Regression Model Evaluation

In [34]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error as mean_squared_error, mean_absolute_error as mae

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [35]:
X_train, X_test, y_train, y_true = train_test_split(X,y,test_size=0.8)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [36]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pre = lr.predict(X_test)


## 3. Calculate and print R-squared for both the training and the testing set.

In [37]:
r2_score(y_true,y_pre)

0.6724085900568655

In [38]:
y_pre_train = lr.predict(X_train)
r2_score(y_train,y_pre_train)

0.7912059182278941

## 4. Calculate and print mean squared error for both the training and the testing set.

In [39]:
mse(y_train, y_pre_train)

20.123881849295895

In [40]:
mse(y_true, y_pre)

26.67249299701085

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [41]:
mae(y_train, y_pre_train)

3.5614048439036674

In [42]:
mae(y_true, y_pre)

3.527008437184292

## Classification Model Evaluation

In [43]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [77]:
data.sample(7)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
121                5.6               2.8                4.9               2.0   
135                7.7               3.0                6.1               2.3   
127                6.1               3.0                4.9               1.8   
72                 6.3               2.5                4.9               1.5   
84                 5.4               3.0                4.5               1.5   
90                 5.5               2.6                4.4               1.2   
138                6.0               3.0                4.8               1.8   

     class  
121      2  
135      2  
127      2  
72       1  
84       1  
90       1  
138      2

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.8)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [79]:
from sklearn.linear_model import LogisticRegression
from numpy import ravel # daba un Warning por tema dimensiones de y_train y había que pasarlo a una array unidemensional.
logr= LogisticRegression()
logr.fit(X_train,ravel(y_train))

y_pred_train = logr.predict(X_train)
y_pred_test = logr.predict(X_test)


In [80]:
y_pred_train

array([1, 2, 2, 0, 2, 0, 1, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1, 0, 0,
       2, 0, 0, 2, 1, 0, 1, 1])

In [81]:
y_pred_test

array([1, 1, 2, 0, 2, 0, 0, 1, 0, 2, 0, 0, 2, 2, 2, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 2, 2, 2, 1, 2, 0, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       2, 2, 2, 1, 1, 1, 1, 2, 0, 2, 2, 0, 0, 2, 1, 2, 0, 2, 0, 1, 0, 2,
       0, 2, 2, 1, 0, 1, 2, 1, 1, 2, 2, 2, 1, 0, 1, 0, 0, 0, 2, 2, 2, 1,
       0, 0, 2, 0, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 0, 1, 1, 1,
       1, 2, 2, 1, 1, 0, 0, 1, 2, 2])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [82]:
from sklearn.metrics import accuracy_score 

accuracy_score(y_train,y_pred_train)

1.0

In [84]:
round(accuracy_score(y_test,y_pred_test),2)

0.96

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [69]:
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_train, y_pred_train)

1.0

In [85]:
round(balanced_accuracy_score(y_test, y_pred_test),2)

0.96

## 10. Calculate and print the precision score for both the training and the testing set.

In [89]:
y_pred_train

array([1, 2, 2, 0, 2, 0, 1, 0, 2, 2, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1, 0, 0,
       2, 0, 0, 2, 1, 0, 1, 1])

In [91]:
from sklearn.metrics import precision_score

precision_score(y_true=y_train,y_pred=y_pred_train, average='micro')

1.0

In [96]:
round(precision_score(y_true=y_test,y_pred=y_pred_test, average='micro'),2)

0.96

## 11. Calculate and print the recall score for both the training and the testing set.

In [99]:
from sklearn.metrics import recall_score
recall_score(y_true=y_train,y_pred=y_pred_train, average='micro')

1.0

In [104]:
round(recall_score(y_true=y_test,y_pred=y_pred_test,average='micro'),2)

0.96

## 12. Calculate and print the F1 score for both the training and the testing set.

In [105]:
from sklearn.metrics import f1_score

round(f1_score(y_true=y_train,y_pred=y_pred_train, average='micro'))

1

In [107]:
round(f1_score(y_true=y_test, y_pred=y_pred_test, average='micro'))

1

## 13. Generate confusion matrices for both the training and the testing set.

In [108]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_true=y_train,y_pred=y_pred_train) #entiendo que no hay que normalizarlo

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [111]:
confusion_matrix(y_true=y_train,y_pred=y_pred_train, normalize='true') #normalizada  sobre los valores true sería

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
confusion_matrix(y_true=y_test,y_pred=y_pred_test) #entiendo que no hay que normalizarlo

array([[40,  0,  0],
       [ 1, 37,  3],
       [ 0,  1, 38]])

In [114]:
confusion_matrix(y_true=y_test,y_pred=y_pred_test, normalize='true') #normalizada  sobre los valores true sería

array([[1.        , 0.        , 0.        ],
       [0.02439024, 0.90243902, 0.07317073],
       [0.        , 0.02564103, 0.97435897]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.