# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [70]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score , recall_score, f1_score, fbeta_score
from sklearn.metrics import precision_recall_fscore_support, classification_report, confusion_matrix

## Regression Model Evaluation

In [4]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

Creamos las 4 variables con las que trabajar, y el train test nos divide el dataset en 4 partes, 2( features y target) para entrenar y 2 para testear.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

Llamamos a la funcion, entrenamos y predecimos, primero con el test ( se hace al revés), y luego con con el train. Nos da una lista de valores que serías las predicciones realizadas, la lista lógicamente tiene el mismo tamaño que los datos que le hemos dado en cada predicción.

In [18]:
boston_model=LinearRegression()
boston_model.fit (X_train, y_train)
y_pred= boston_model.predict (X_test)
y_pred2=boston_model.predict (X_train)

## 3. Calculate and print R-squared for both the training and the testing set.

In [20]:
print("R2: ", metrics.r2_score(y_test,y_pred))
print("R2: ", metrics.r2_score(y_train,y_pred2))

R2:  0.7220257852231711
R2:  0.7434933749635788


## 4. Calculate and print mean squared error for both the training and the testing set.

In [22]:
print("RMSE: ", np.sqrt(metrics.mean_squared_error(y_test,y_pred)))
print("RMSE: ", np.sqrt(metrics.mean_squared_error(y_train,y_pred2)))

RMSE:  4.929032572806593
RMSE:  4.632477865964201


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [21]:
print("MAE: ", metrics.mean_absolute_error(y_test, y_pred))
print("MAE: ", metrics.mean_absolute_error(y_train, y_pred2))

MAE:  3.295378517851354
MAE:  3.2654576160766533


## Classification Model Evaluation

In [2]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [41]:
LRiris_model = LogisticRegression(max_iter=100000)
LRiris_model.fit (X_train,y_train)
y_pred=LRiris_model.predict (X_train)
y_pred2=LRiris_model.predict (X_test)

C:\Users\asiok\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


## 8. Calculate and print the accuracy score for both the training and the testing set.

% de acierto de la prediccion sobre lo real

In [42]:
print (accuracy_score(y_train, y_pred))
print (accuracy_score (y_test, y_pred2))

0.975
0.9333333333333333


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [43]:
print (balanced_accuracy_score(y_train, y_pred))
print (balanced_accuracy_score(y_test, y_pred2))

0.9751540449214868
0.9220779220779222


## 10. Calculate and print the precision score for both the training and the testing set.

Es el porcentaje de acierto sobre mis propias previsiones, es decir, el 100% de los positivos han acertado para el 0, el 97 y 100 para el 1 y el 97 y 84 para el 2. En este caso lo que "queda fuera", (1-precision_score) son nuestros falsos positivos. (los numeros han variado despúes de reiniciar kernel y obtener un train/test diferente)

Resultado de dividir nuestros flores x coincidentes con las reales entre todas las flores que hemos dicho que son x.

Voy a sacar todos los valores del parámetro average y así los veo 

In [81]:
print (precision_score(y_train, y_pred, average="micro"))
print (precision_score(y_test, y_pred2, average="micro"))

0.975
0.9333333333333333


In [82]:
print (precision_score(y_train, y_pred, average="macro"))
print (precision_score(y_test, y_pred2, average="macro"))

0.9760765550239235
0.9220779220779222


In [83]:
print (precision_score(y_train, y_pred, average="weighted"))
print (precision_score(y_test, y_pred2, average="weighted"))

0.9751594896331739
0.9333333333333333


In [84]:
print (precision_score(y_train, y_pred, average=None))
print (precision_score(y_test, y_pred2, average=None))

[1.         0.97368421 0.95454545]
[1.         0.90909091 0.85714286]


Acertadas de la flor 1, entre las que hemos dicho que eran 1:

In [100]:
37/38

0.9736842105263158

## 11. Calculate and print the recall score for both the training and the testing set.

Positivos correctamente sobre el total de positivos, para el 0, el 1 y el 2, es decir, para clase 0, nuestro modelo acierta los positivos en el 100% de los casos, para la clase 1, los acierta en 97 y 94 y para la clase 2 en un 97 y 100. En este caso lo que "queda fuera", (1 - recall_score), son los positivos reales que no hemos acertado, los falsos negativos.

En otras palabras, es el resultado de dividir los positivos acertados en la predicción entre los positivos reales.

In [85]:
print (recall_score(y_train, y_pred, average= "micro"))
print (recall_score(y_test, y_pred2, average= "micro"))

0.975
0.9333333333333333


In [86]:
print (recall_score(y_train, y_pred, average= "macro"))
print (recall_score(y_test, y_pred2, average= "macro"))

0.9751540449214868
0.9220779220779222


In [87]:
print (recall_score(y_train, y_pred, average= "weighted"))
print (recall_score(y_test, y_pred2, average= "weighted"))

0.975
0.9333333333333333


In [88]:
print (recall_score(y_train, y_pred, average=None))
print (recall_score(y_test, y_pred2, average=None))

[1.         0.94871795 0.97674419]
[1.         0.90909091 0.85714286]


Acertadas de la clase 1, entre las que realmente eran 1:

In [101]:
37/39 

0.9487179487179487

## 12. Calculate and print the F1 score for both the training and the testing set.

Media armónica de recall y precision, es decir: 2/(1/recall) +(1/precission), esta media tiende dar mayor peso a los valores inferiores.

In [89]:
print (f1_score(y_train, y_pred, average="micro"))
print (f1_score(y_test, y_pred2, average="micro"))

0.975
0.9333333333333333


In [90]:
print (f1_score(y_train, y_pred, average="macro"))
print (f1_score(y_test, y_pred2, average="macro"))

0.9755187341394239
0.9220779220779222


In [91]:
print (f1_score(y_train, y_pred, average="weighted"))
print (f1_score(y_test, y_pred2, average="weighted"))

0.974981340498582
0.9333333333333333


In [92]:
print (precision_score(y_train, y_pred, average=None))
print (precision_score(y_test, y_pred2, average=None))

[1.         0.97368421 0.95454545]
[1.         0.90909091 0.85714286]


En la vista inferior el resumen

In [96]:
precision_recall_fscore_support (y_train, y_pred, average=None)

(array([1.        , 0.97368421, 0.95454545]),
 array([1.        , 0.94871795, 0.97674419]),
 array([1.        , 0.96103896, 0.96551724]),
 array([38, 39, 43], dtype=int64))

In [95]:
precision_recall_fscore_support (y_test, y_pred2, average=None)

(array([1.        , 0.90909091, 0.85714286]),
 array([1.        , 0.90909091, 0.85714286]),
 array([1.        , 0.90909091, 0.85714286]),
 array([12, 11,  7], dtype=int64))

In [66]:
print (classification_report (y_train, y_pred)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.97      0.95      0.96        39
           2       0.95      0.98      0.97        43

    accuracy                           0.97       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.97      0.97       120



In [73]:
print (classification_report (y_test, y_pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.91      0.91      0.91        11
           2       0.86      0.86      0.86         7

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30



Se aprecia que los porcentajes de acierto bajan en el test frente a los obtenidos en sobre los datos entrenados. Sería significativo y podríamos decir que hay cierto overfitting en nuestro modelo.

## 13. Generate confusion matrices for both the training and the testing set.

In [76]:
confusion_matrix(y_train, y_pred)

array([[38,  0,  0],
       [ 0, 37,  2],
       [ 0,  1, 42]], dtype=int64)

In [97]:
# disculpadme que lo ponga así, está pensado por si lo necesito entender otra vez dentro de 3 años xd

In [98]:
confusion_matrix(y_test, y_pred2)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  1,  6]], dtype=int64)

Y aquí vemos porque nos daba el mismo resultado en recall y precission

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [102]:
# me he liado intentando aprender bien la diferencia entre recall y precision y perdiendome en la documentación de sklearn. Si mañana madrugo lo hago