# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score , recall_score, f1_score, fbeta_score
from sklearn.metrics import precision_recall_fscore_support, classification_report, confusion_matrix
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import SGDRegressor, SGDClassifier
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier
from sklearn.model_selection import cross_val_score


## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

Creamos las 4 variables con las que trabajar, y el train test nos divide el dataset en 4 partes, 2( features y target) para entrenar y 2 para testear.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

Llamamos a la funcion, entrenamos y predecimos, primero con el test ( se hace al revés), y luego con con el train. Nos da una lista de valores que serías las predicciones realizadas, la lista lógicamente tiene el mismo tamaño que los datos que le hemos dado en cada predicción.

In [18]:
boston_model=LinearRegression()
boston_model.fit (X_train, y_train)
y_pred= boston_model.predict (X_test)
y_pred2=boston_model.predict (X_train)

## 3. Calculate and print R-squared for both the training and the testing set.

In [20]:
print("R2: ", metrics.r2_score(y_test,y_pred))
print("R2: ", metrics.r2_score(y_train,y_pred2))

R2:  0.7220257852231711
R2:  0.7434933749635788


## 4. Calculate and print mean squared error for both the training and the testing set.

In [22]:
print("RMSE: ", np.sqrt(metrics.mean_squared_error(y_test,y_pred)))
print("RMSE: ", np.sqrt(metrics.mean_squared_error(y_train,y_pred2)))

RMSE:  4.929032572806593
RMSE:  4.632477865964201


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [21]:
print("MAE: ", metrics.mean_absolute_error(y_test, y_pred))
print("MAE: ", metrics.mean_absolute_error(y_train, y_pred2))

MAE:  3.295378517851354
MAE:  3.2654576160766533


## Classification Model Evaluation

In [2]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [41]:
LRiris_model = LogisticRegression(max_iter=100000)
LRiris_model.fit (X_train,y_train)
y_pred=LRiris_model.predict (X_train)
y_pred2=LRiris_model.predict (X_test)

C:\Users\asiok\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


## 8. Calculate and print the accuracy score for both the training and the testing set.

% de acierto de la prediccion sobre lo real

In [42]:
print (accuracy_score(y_train, y_pred))
print (accuracy_score (y_test, y_pred2))

0.975
0.9333333333333333


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [43]:
print (balanced_accuracy_score(y_train, y_pred))
print (balanced_accuracy_score(y_test, y_pred2))

0.9751540449214868
0.9220779220779222


## 10. Calculate and print the precision score for both the training and the testing set.

Es el porcentaje de acierto sobre mis propias previsiones, es decir, el 100% de los positivos han acertado para el 0, el 97 y 100 para el 1 y el 97 y 84 para el 2. En este caso lo que "queda fuera", (1-precision_score) son nuestros falsos positivos. (los numeros han variado despúes de reiniciar kernel y obtener un train/test diferente)

Resultado de dividir nuestros flores x coincidentes con las reales entre todas las flores que hemos dicho que son x.

Voy a sacar todos los valores del parámetro average y así los veo 

In [81]:
print (precision_score(y_train, y_pred, average="micro"))
print (precision_score(y_test, y_pred2, average="micro"))

0.975
0.9333333333333333


In [82]:
print (precision_score(y_train, y_pred, average="macro"))
print (precision_score(y_test, y_pred2, average="macro"))

0.9760765550239235
0.9220779220779222


In [83]:
print (precision_score(y_train, y_pred, average="weighted"))
print (precision_score(y_test, y_pred2, average="weighted"))

0.9751594896331739
0.9333333333333333


In [84]:
print (precision_score(y_train, y_pred, average=None))
print (precision_score(y_test, y_pred2, average=None))

[1.         0.97368421 0.95454545]
[1.         0.90909091 0.85714286]


Acertadas de la flor 1, entre las que hemos dicho que eran 1:

In [100]:
37/38

0.9736842105263158

## 11. Calculate and print the recall score for both the training and the testing set.

Positivos correctamente sobre el total de positivos, para el 0, el 1 y el 2, es decir, para clase 0, nuestro modelo acierta los positivos en el 100% de los casos, para la clase 1, los acierta en 97 y 94 y para la clase 2 en un 97 y 100. En este caso lo que "queda fuera", (1 - recall_score), son los positivos reales que no hemos acertado, los falsos negativos.

En otras palabras, es el resultado de dividir los positivos acertados en la predicción entre los positivos reales.

In [85]:
print (recall_score(y_train, y_pred, average= "micro"))
print (recall_score(y_test, y_pred2, average= "micro"))

0.975
0.9333333333333333


In [86]:
print (recall_score(y_train, y_pred, average= "macro"))
print (recall_score(y_test, y_pred2, average= "macro"))

0.9751540449214868
0.9220779220779222


In [87]:
print (recall_score(y_train, y_pred, average= "weighted"))
print (recall_score(y_test, y_pred2, average= "weighted"))

0.975
0.9333333333333333


In [88]:
print (recall_score(y_train, y_pred, average=None))
print (recall_score(y_test, y_pred2, average=None))

[1.         0.94871795 0.97674419]
[1.         0.90909091 0.85714286]


Acertadas de la clase 1, entre las que realmente eran 1:

In [101]:
37/39 

0.9487179487179487

## 12. Calculate and print the F1 score for both the training and the testing set.

Media armónica de recall y precision, es decir: 2/(1/recall) +(1/precission), esta media tiende dar mayor peso a los valores inferiores.

In [89]:
print (f1_score(y_train, y_pred, average="micro"))
print (f1_score(y_test, y_pred2, average="micro"))

0.975
0.9333333333333333


In [90]:
print (f1_score(y_train, y_pred, average="macro"))
print (f1_score(y_test, y_pred2, average="macro"))

0.9755187341394239
0.9220779220779222


In [91]:
print (f1_score(y_train, y_pred, average="weighted"))
print (f1_score(y_test, y_pred2, average="weighted"))

0.974981340498582
0.9333333333333333


In [92]:
print (precision_score(y_train, y_pred, average=None))
print (precision_score(y_test, y_pred2, average=None))

[1.         0.97368421 0.95454545]
[1.         0.90909091 0.85714286]


En la vista inferior el resumen

In [96]:
precision_recall_fscore_support (y_train, y_pred, average=None)

(array([1.        , 0.97368421, 0.95454545]),
 array([1.        , 0.94871795, 0.97674419]),
 array([1.        , 0.96103896, 0.96551724]),
 array([38, 39, 43], dtype=int64))

In [95]:
precision_recall_fscore_support (y_test, y_pred2, average=None)

(array([1.        , 0.90909091, 0.85714286]),
 array([1.        , 0.90909091, 0.85714286]),
 array([1.        , 0.90909091, 0.85714286]),
 array([12, 11,  7], dtype=int64))

In [66]:
print (classification_report (y_train, y_pred)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.97      0.95      0.96        39
           2       0.95      0.98      0.97        43

    accuracy                           0.97       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.97      0.97       120



In [73]:
print (classification_report (y_test, y_pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.91      0.91      0.91        11
           2       0.86      0.86      0.86         7

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30



Se aprecia que los porcentajes de acierto bajan en el test frente a los obtenidos en sobre los datos entrenados. Sería significativo y podríamos decir que hay cierto overfitting en nuestro modelo.

## 13. Generate confusion matrices for both the training and the testing set.

In [76]:
confusion_matrix(y_train, y_pred)

array([[38,  0,  0],
       [ 0, 37,  2],
       [ 0,  1, 42]], dtype=int64)

In [97]:
# disculpadme que lo ponga así, está pensado por si lo necesito entender otra vez dentro de 3 años xd

In [98]:
confusion_matrix(y_test, y_pred2)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  1,  6]], dtype=int64)

Y aquí vemos porque nos daba el mismo resultado en recall y precission

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

Vamos con el primer data, nos encontramos ante un problema de regresión, por lo que usaremos esos modelos. La diferencia, por lo que hemos visto hasta ahora creo que la podemos simplificar a:
* regresión: predecimos un valor numérico sin rango ( Pe: si eres rubio, trabajas y tienes 3 hermanos: ganarás x dinero)
* clasificación: predecimos un valor categórico que puede ser clasificado por numeros ( Pe: si eres rubio, trabajas y tienes 3 hermanos: eres ejecutivo) 

De lo que también se deduce que las [métricas que utilicemos](https://fayrix.com/machine-learning-metrics_es) no pueden ser las mismas

In [3]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

Hacemos un diccionario que llama a distintos modelos, después iteramos sobre el para entrenarlo primero, y printear metricas para ytrain e ytest después. Con esto echaremos un vistazo rápido a varios modelos.

In [24]:
boston_models= { "Linnear":LinearRegression (),
                 "ridge": Ridge(),
                 "laso": Lasso(),
                 "sgd": SGDRegressor (),
                 "knn": KNeighborsRegressor(),
                 "gradient": GradientBoostingRegressor ()
                 
    
    }

In [32]:
for name, model in boston_models.items():
    model.fit(X_train,y_train.values.ravel())

[values.ravel error](https://stackoverflow.com/questions/34165731/a-column-vector-y-was-passed-when-a-1d-array-was-expected)

In [26]:
for name, model in boston_models.items():
    y_pred = model.predict(X_test)
    y_pred2= model.predict (X_train)
    print(f"--------{name}test--------")
    print("MAE: ", metrics.mean_absolute_error(y_test, y_pred))
    print("MSE: ", metrics.mean_squared_error(y_test,y_pred))
    print("RMSE: ", np.sqrt(metrics.mean_squared_error(y_test,y_pred)))
    print("R2: ", metrics.r2_score(y_test,y_pred))
    print("\n")
    print(f"--------{name}train--------")
    print("MAE: ", metrics.mean_absolute_error(y_train, y_pred2))
    print("MSE: ", metrics.mean_squared_error(y_train,y_pred2))
    print("RMSE: ", np.sqrt(metrics.mean_squared_error(y_train,y_pred2)))
    print("R2: ", metrics.r2_score(y_train,y_pred2))
    print("\n")
    print("\n")

--------Linneartest--------
MAE:  3.2716385742562473
MSE:  24.554792940076364
RMSE:  4.955279299905946
R2:  0.6776857673620341


--------Linneartrain--------
MAE:  3.3517643226774454
MSE:  21.452677426234516
RMSE:  4.631703512341276
R2:  0.7519664132413573




--------ridgetest--------
MAE:  3.276701864031989
MSE:  24.75912343694789
RMSE:  4.975854040960997
R2:  0.6750036585181761


--------ridgetrain--------
MAE:  3.3348425108588557
MSE:  21.63411941426411
RMSE:  4.651249231578986
R2:  0.7498686001719004




--------lasotest--------
MAE:  3.733442390489292
MSE:  29.692599301946128
RMSE:  5.449091603372633
R2:  0.6102452428579264


--------lasotrain--------
MAE:  3.630613422815236
MSE:  26.22711643795852
RMSE:  5.121241689078785
R2:  0.6967648545123706




--------sgdtest--------
MAE:  39941849867502.14
MSE:  1.8321181010352744e+27
RMSE:  42803248720573.47
R2:  -2.4048980631944812e+25


--------sgdtrain--------
MAE:  42469105418114.95
MSE:  2.0534295376828826e+27
RMSE:  45314782772103.

Vemos claramente que el [gradientboosting](https://interactivechaos.com/es/manual/tutorial-de-machine-learning/gradient-boosting) tiene un R2 lo suficientemente destacado como para elegirlo a simple vista. En cualquier caso, por seguir indagando vamos a imaginarnos que tenemos unos resultados ajustados, para ello utilizaré el cross validation, que sencillamente hace tanto splits como le digamos ( en este caso 5) con la particularidad de qué, aún siendo aleatorios, no se repiten los datos en los splits. Y nos devuelve un r2 para cada split. Es meramente informativo, pero es muy util porque el split inicial por lo que sea puede estar mal balanceado.

Seguimos iterando por el diccionario de modelos, y le pedimos la media de los r2

In [31]:
for name, model in boston_models.items():
    scores = cross_val_score(model, X_train, y_train.values.ravel(), scoring = "r2", cv=5)
    print(f"{name} r2 {np.mean(scores)}" )

Linnear r2 0.7261800329428449
ridge r2 0.7257207244999027
laso r2 0.6756914036919176
sgd r2 -4.6930600694861196e+26
knn r2 0.48885187027281435
gradient r2 0.8611459136563401


Podemos sacar conclusiones interesantes sobre la utilidad del cross validation, como vemos gradient ha bajado en 4 puntos y linnear y ridge han subido en 5. Para nuestro caso es irrelevante porque la diferencia era enorme, pero sí que es cierto que en otros casos nos podemos encontrar con una diferencia de 10-15 puntos que puede darse la vuelta al hacer este proceso.

Vamos con el segundo data, en este caso de clasificación:

In [33]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

Y hasta aquí, el otro data para otro día